backend:
  name: github
  repo: drskiboss/big-shapes
  branch: main
  site_domain: https://big-shapes.com
  auth_endpoint: https://api.netlify.com/auth/done

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"

      - name: "date"
        label: "Date"
        widget: "datetime"

      - name: "body"
        label: "Body"
        widget: "markdown"
