backend:
  name: github
  repo: drskiboss/big-shapes
  branch: main
  auth_scope: repo
  base_url: https://big-shapes.com
  auth_endpoint: /admin
  client_id: "Ov23liJEWMbeA2KbuFAb"
  client_secret: "1d7f04fbfcf9a582e4efd760f0e9c287ef6f8a4e"


media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"

      - name: "date"
        label: "Date"
        widget: "datetime"

      - name: "body"
        label: "Body"
        widget: "markdown"
